# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_uSyWztDg7ePVh048z0N76K4hrfxk4A
"""

import csv
import requests
import pprint

from google.colab import drive
drive.mount('/content/drive')

csv_file=open('/content/drive/MyDrive/rainData.csv')
csv_reader = csv.reader(csv_file, delimiter=',')
next(csv_reader)
next(csv_reader)
line_count = 0
rain_data=list()
for row in csv_reader:
    # next(csv_reader)
    # next(csv_reader)
    rain_data.append(row)
csv_file.close()
print(rain_data)

val = str(input("Enter city name:[San Jose]") or "San Jose")
response=requests.get("https://nominatim.openstreetmap.org/search.php?city="+val+"&format=jsonv2&namedetails=0&addressdetails=0&limit=1")
city_data=response.json()
c_lat=city_data[0]['lat']
c_lon=city_data[0]['lon']
  
dist_thresh=0.05
rain_thresh=8.0
dates=list()

for row in rain_data:
     t,lat,lon,rain=row
     if rain == ' ':
       rain = 0
     t=t[:10]
     lat_diff=abs(float(lat)-float(c_lat))
     lon_diff=abs(float(lon)-float(c_lon))
     try:
      if rain != " ":
       
         if float(rain) >= rain_thresh:
            if lat_diff<dist_thresh:
                 if lon_diff<dist_thresh:
                     dates.append((t,rain))
     except:
          print("not converted into float")

print(dates)

for item in dates:
     print(item)
print("number of rainy 5-days: "+str(len(dates)))

